name: Haskell CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: '9.6.5'
          cabal-version: '3.10.2.1'
      - name: Cache cabal store
        uses: actions/cache@v4
        with:
          path: ~/.cabal/store
          key: ${{ runner.os }}-cabal-${{ hashFiles('**/*.cabal') }}
          restore-keys: ${{ runner.os }}-cabal-
      - name: Build (all components)
        run: cabal v2-build all --ghc-options="-Wall"
      - name: Run tests
        run: cabal v2-test --test-show-details=direct
      - name: Smoke run executable (non-interactive exit)
        run: |
          echo 6 | cabal v2-run vehicle-register
